LMS/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls' , namespace="app"))
]

app/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import user_login, views


app_name = 'app'
urlpatterns = [
    path('' , views.home , name='home'),
    path('404' , views.page_notefound , name='404'),
    path('pagecourse' , views.pagecourse , name='pagecourse'),
    path('course/filter-data',views.filter_data,name="filter-data"),
    path('course/<slug:slug>',views.course_details,name="course_details"),
    path('search',views.SEARCH_COURSE,name='search_course'),
    path('about_uspage' , views.about_uspage , name='about_uspage'),
    path('contact_uspage' , views.contact_uspage , name='contact_uspage'),
    path('accounts/register', user_login.REGISTER , name = 'register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('doLogin/', user_login.DOLOGIN, name = 'doLogin'),
    path('accounts/profile' , user_login.Profile , name='profile'),
    path('accounts/profile/update', user_login.PROFILE_UPDATE , name='profile_update'),
    path('accounts/password_reset_confirm', user_login.password_reset_confirm , name='password_reset_confirm'),
    
    path('chackout/<slug:slug>',views.chackout,name="chackout"),
    path('mycourse',views.mycourse,name="mycourse"),
    path('course/watchcourse/<slug:slug>',views.watchcourse,name="watchcourse"),

] + static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)
  

app/templates/Components/modle.html
{% load static %} 
    <!-- MODALS
        ================================================== -->
        <!-- Modal Sidebar account -->
        <div class="modal fade" id="modalExample" tabindex="-1" role="dialog" aria-labelledby="modalExampleTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-body">
      
                  <!-- Close -->
                  <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                  </button>
      
                  <!-- Heading -->
                  <h2 class="fw-bold text-center mb-1" id="modalExampleTitle">
                    Schedule a demo with us
                  </h2>
      
                  <!-- Text -->
                  <p class="font-size-lg text-center text-muted mb-6 mb-md-8">
                    We can help you solve company communication.
                  </p>
      
                  <!-- Form -->
                  <form>
                    <div class="row">
                      <div class="col-12 col-md-6">
      
                        <!-- First name -->
                        <div class="form-label-group">
                          <input type="text" class="form-control form-control-flush" id="registrationFirstNameModal" placeholder="First name">
                          <label for="registrationFirstNameModal">First name</label>
                        </div>
      
                      </div>
                      <div class="col-12 col-md-6">
      
                        <!-- Last name -->
                        <div class="form-label-group">
                          <input type="text" class="form-control form-control-flush" id="registrationLastNameModal" placeholder="Last name">
                          <label for="registrationLastNameModal">Last name</label>
                        </div>
      
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-12 col-md-6">
      
                        <!-- Email -->
                        <div class="form-label-group">
                          <input type="email" class="form-control form-control-flush" id="registrationEmailModal" placeholder="Email">
                          <label for="registrationEmailModal">Email</label>
                        </div>
      
                      </div>
                      <div class="col-12 col-md-6">
      
                        <!-- Password -->
                        <div class="form-label-group">
                          <input type="password" class="form-control form-control-flush" id="registrationPasswordModal" placeholder="Password">
                          <label for="registrationPasswordModal">Password</label>
                        </div>
      
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-12">
      
                        <!-- Submit -->
                        <button class="btn btn-block btn-primary mt-3 lift">
                          Request a demo
                        </button>
      
                      </div>
                    </div>
                  </form>
      
                </div>
              </div>
            </div>
          </div>
      
          <div class="modal modal-sidebar left fade-left fade" id="accountModal">
              <div class="modal-dialog">
                  <div class="modal-content">
                      <!-- Signin -->
                      <div class="collapse show" id="collapseSignin" data-bs-parent="#accountModal">
                          <div class="modal-header">
                              <h5 class="modal-title " center-text>!تسجيل الدخول إلى حسابك  </h5>
                              <button type="button" class="close text-primary" data-bs-dismiss="modal" aria-label="Close">
                                  <!-- Icon -->
                                  <svg width="16" height="17" viewBox="0 0 16 17" xmlns="http://www.w3.org/2000/svg">
                                      <path d="M0.142135 2.00015L1.55635 0.585938L15.6985 14.7281L14.2843 16.1423L0.142135 2.00015Z" fill="currentColor"></path>
                                      <path d="M14.1421 1.0001L15.5563 2.41431L1.41421 16.5564L0 15.1422L14.1421 1.0001Z" fill="currentColor"></path>
                                  </svg>
      
                              </button>
                          </div>
      
                          <div class="modal-body">
                              <!-- Form Signin -->
                              <form class="mb-5" method='post'  method="post" action="{%url 'app:doLogin'%}"> 
                              {% csrf_token %}
                                  
                                  <div class="form-group mb-5">
                                      <label for="modalSigninEmail " text-center>
                                    البريد الالكتروني
                                      </label>
                                      <input type="email" class="form-control" id="modalSigninEmail" placeholder="creativelayers" name="email">
                                  </div>
      
                                  <!-- Password -->
                                  <div class="form-group mb-5">
                                      <label for="modalSigninPassword">
                                          كلمة المرور 
                                      </label>
                                      <input type="password" class="form-control" id="modalSigninPassword" placeholder="**********" name="password">
                                  </div>
      
                                  <div class="d-flex align-items-center mb-5 font-size-sm">
                                      <div class="form-check">
                                          <input class="form-check-input text-gray-800" type="checkbox" id="autoSizingCheck">
                                          <label class="form-check-label text-gray-800" for="autoSizingCheck">
                                            تذكرنى
                                          </label>
                                      </div>
      
                                      <div class="ms-auto">
                                          <a class="text-gray-800" data-bs-toggle="collapse" href="#collapseForgotPassword" role="button" aria-expanded="false" aria-controls="collapseForgotPassword">هل نسيت كلمة السر</a>
                                      </div>
                                  </div>
      
                                  <!-- Submit -->
                                  <button class="btn btn-block btn-primary" type="submit">
                                    تسجيل الدخول
                                  </button>
                              </form>
      
                              <!-- Text -->
                              <p class="mb-0 font-size-sm text-center">
                                ليس لديك حساب؟ <a class="text-underline" data-bs-toggle="collapse" href="#collapseSignup" role="button" aria-expanded="false" aria-controls="collapseSignup">Sign up</a>
                              </p>
                          </div>
                      </div>
      
                      <!-- Signup -->
                      <div class="collapse" id="collapseSignup" data-bs-parent="#accountModal">
                          <div class="modal-header">
                              <h5 class="modal-title">Sign Up and Start Learning!</h5>
                              <button type="button" class="close text-primary" data-bs-dismiss="modal" aria-label="Close">
                                  <!-- Icon -->
                                  <svg width="16" height="17" viewBox="0 0 16 17" xmlns="http://www.w3.org/2000/svg">
                                      <path d="M0.142135 2.00015L1.55635 0.585938L15.6985 14.7281L14.2843 16.1423L0.142135 2.00015Z" fill="currentColor"></path>
                                      <path d="M14.1421 1.0001L15.5563 2.41431L1.41421 16.5564L0 15.1422L14.1421 1.0001Z" fill="currentColor"></path>
                                  </svg>
      
                              </button>
                          </div>
      
                          <div class="modal-body">
                              <!-- Form Signup -->
                              <form class="mb-5"  method='post' action="{%url 'app:register'%}">
                                {% csrf_token %}
      
                                  <!-- Username -->
                                  <div class="form-group mb-5">
                                      <label for="modalSignupUsername">
                                          اسم المستخدم
                                      </label>
                                      <input type="text" class="form-control" id="modalSignupUsername" placeholder="John" name ='username'>
                                  </div>
      
                                  <!-- Email -->
                                  <div class="form-group mb-5">
                                      <label for="modalSignupEmail">
                                         البريد  الإلكتروني
                                      </label>
                                      <input type="email" class="form-control" id="modalSignupEmail" placeholder="johndoe@creativelayers.com" name ='email'>
                                  </div>
      
                                  <!-- Password -->
                                  <div class="form-group mb-5">
                                      <label for="modalSignupPassword">
                                         كلمةالمرور
                                      </label>
                                      <input type="password" class="form-control" id="modalSignupPassword" placeholder="**********" name ='password'>
                                  </div>
      
                                  <!-- Submit -->
                                  <button class="btn btn-block btn-primary" type="submit">
                                      SIGN UP
                                  </button>
      
                              </form>
      
                              <!-- Text -->
                              <p class="mb-0 font-size-sm text-center">
                                  Already have an account? <a class="text-underline" data-bs-toggle="collapse" href="#collapseSignin" role="button" aria-expanded="true" aria-controls="collapseSignin">Log In</a>
                              </p>
                          </div>
                      </div>
      
                      <!-- Forgot Password -->
                      <div class="collapse" id="collapseForgotPassword" data-bs-parent="#accountModal">
                          <div class="modal-header">
                              <h5 class="modal-title">Recover password!</h5>
                              <button type="button" class="close text-primary" data-bs-dismiss="modal" aria-label="Close">
                                  <!-- Icon -->
                                  <svg width="16" height="17" viewBox="0 0 16 17" xmlns="http://www.w3.org/2000/svg">
                                      <path d="M0.142135 2.00015L1.55635 0.585938L15.6985 14.7281L14.2843 16.1423L0.142135 2.00015Z" fill="currentColor"></path>
                                      <path d="M14.1421 1.0001L15.5563 2.41431L1.41421 16.5564L0 15.1422L14.1421 1.0001Z" fill="currentColor"></path>
                                  </svg>
      
                              </button>
                          </div>
      
                          <div class="modal-body">
                              <!-- Form Recover Password -->
                              <form class="mb-5">
                                  <!-- Email -->
                                  <div class="form-group">
                                      <label for="modalForgotpasswordEmail">
                                          Email
                                      </label>
                                      <input type="email" class="form-control" id="modalForgotpasswordEmail" placeholder="johndoe@creativelayers.com">
                                  </div>
      
                                  <!-- Submit -->
                                  <button class="btn btn-block btn-primary" type="submit">
                                      RECOVER PASSWORD
                                  </button>
                              </form>
      
                              <!-- Text -->
                              <p class="mb-0 font-size-sm text-center">
                                  Remember your password? <a class="text-underline" data-bs-toggle="collapse" href="#collapseSignin" role="button" aria-expanded="false" aria-controls="collapseSignin">Log In</a>
                              </p>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      

app/templates/Components/msg.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        {% elif message.tags == 'success' %}
             <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        {% elif message.tags == 'warning' %}
             <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        {% endif %}
    {% endfor %}
 {% endif %}